### ISSUE TITLE
Getting an Error while manually building container

### ISSUE THREAD

**Issue by aakritimadaan** [ai-cfia/finesse-frontend#9]
![finesse container build](https://github.com/ai-cfia/louis-finesse/assets/139572972/7f3757b1-c7b8-49e5-bffe-1088467d1291)

**Comment by rngadam** [comment]
seems to be related to create-react-app not supporting latest version of typescript, requiring an ```overrides``` section into the code:

https://github.com/facebook/create-react-app/issues/13080

this same issues points out create-react-app is no longer officially supported by the React docs and points out vite as the alternative (which also appears to have its own problems)

there's also a vulnerability support that is a little bit weird because it tries to install an older version of react-scripts when we already have 5.0.1 installed:

https://github.com/advisories/GHSA-rp65-9cf3-cjxr
